baseURL = 'https://dudung.github.io/rust'
languageCode = 'en-us'
title = 'rust'
theme = 'default'

enableEmoji = true

ignoreErrors = ['error-missing-instagram-accesstoken']

# url https://chatgpt.com/share/674c42d8-7298-800a-9d2f-57af4c77c925 [2024120]
# paginate = 16

[pagination]
pagerSize = 20

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 2
  identifier = 'home'
  url = '/'

[[menu.main]]
  name = 'OSF'
  weight = 1
  identifier = 'osf'
  url = '/tags/osf'
